import React, { useState } from 'react';
import { flattenBackends } from './store.js';
import { formatDateTime } from './format.js';
import { Heading, Empty, Metric, Status } from './components.jsx';
export default function Backends({ state, onSelect }) {
  const [search, setSearch] = useState(''), [project, setProject] = useState(''), [lb, setLb] = useState(''), [status, setStatus] = useState('');
  const rows = flattenBackends({ ...state.scanResult, lastScanTime: state.lastScanTime });
  const filtered = rows.filter(r => (!project || r.project === project) && (!lb || r.loadBalancer === lb) && (!status || r.status === status) && [r.project, r.loadBalancer, r.forwardingRule, r.backendService, r.cloudArmorPolicy].join(' ').toLowerCase().includes(search.toLowerCase()));
  const options = key => [...new Set(rows.map(r => r[key]))].map(value => <option key={value}>{value}</option>);
  const select = r => onSelect({ type: 'Backend Service', name: r.backendService, status: r.status, chain: [['Project', r.project], ['Load Balancer', r.loadBalancer], ['Forwarding Rule', r.forwardingRule], ['Target Proxy', r.hierarchy.target_proxy?.name], ['URL Map', r.hierarchy.url_map?.name], ['Backend Service', r.backendService], ['Cloud Armor Policy', r.cloudArmorPolicy]] });
  return <><Heading title="Unprotected Backends">Public backend services behind external load balancers without an attached Cloud Armor policy.</Heading>{!rows.length ? <Empty /> : <><section className="panel"><div className="filter-row"><input type="search" aria-label="Search backends" placeholder="Search backends, LBs, projects..." value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="Project" value={project} onChange={e => setProject(e.target.value)}><option value="">All Projects</option>{options('project')}</select><select aria-label="Load balancer" value={lb} onChange={e => setLb(e.target.value)}><option value="">All Load Balancers</option>{options('loadBalancer')}</select><select aria-label="Status" value={status} onChange={e => setStatus(e.target.value)}><option value="">All Statuses</option><option value="PROTECTED">Protected</option><option value="UNPROTECTED">Unprotected</option></select></div><div className="metric-grid three"><Metric label="Total Public Backends" value={rows.length} /><Metric label="Protected" value={rows.filter(r => r.status === 'PROTECTED').length} /><Metric label="Unprotected" value={rows.filter(r => r.status === 'UNPROTECTED').length} /></div></section><section className="panel table-panel"><div className="table-wrap"><table className="data-table"><thead><tr>{['Project', 'Load Balancer', 'Forwarding Rule', 'Backend Service', 'Cloud Armor Policy', 'Status', 'Last Detected'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map((r, i) => <tr key={i} className="clickable-row" tabIndex={0} onClick={() => select(r)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); select(r); } }}><td>{r.project}</td><td>{r.loadBalancer}</td><td><code>{r.forwardingRule}</code></td><td><code>{r.backendService}</code></td><td>{r.cloudArmorPolicy}</td><td><Status value={r.status} /></td><td>{formatDateTime(r.lastDetected)}</td></tr>)}{!filtered.length && <tr><td colSpan={7} className="empty-inline">No backends match the current filters.</td></tr>}</tbody></table></div></section></>}</>;
}
